## spacing_z resampling

resampling : (1.0, 1.0, 2.0)

- covid의 z 방향 slice 간격을 2.0mm 기준으로 다시 샘플링
- 나머지 source는 1.0으로 샘플링
- slice 수는 증가
- 하지만 실제 해상도가 진짜 좋아지는 건 아니고 보간된 slice가 생김

In [1]:
import SimpleITK as sitk

In [9]:
from pathlib import Path

import nibabel as nib
import numpy as np
import pandas as pd
from scipy.ndimage import zoom

RAW_ROOT = Path(r"C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\raw_data")
VOLUME_ROOT = RAW_ROOT / "volumes"
LABEL_ROOT = RAW_ROOT / "labels"

OUTPUT_ROOT = Path(r"C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\t11_t12_resampled_1x1x2")
OUTPUT_IMAGE_ROOT = OUTPUT_ROOT / "images"
OUTPUT_LABEL_ROOT = OUTPUT_ROOT / "labels"

TARGET_SPACING = (1.0, 1.0, 2.0)

T11_LABEL = 18
T12_LABEL = 19

OUTPUT_IMAGE_ROOT.mkdir(parents=True, exist_ok=True)
OUTPUT_LABEL_ROOT.mkdir(parents=True, exist_ok=True)

In [10]:
def find_label_path(volume_path):
    rel = volume_path.relative_to(VOLUME_ROOT)
    label_dir = LABEL_ROOT / rel.parent
    stem = volume_path.name.replace(".nii.gz", "")

    candidates = [
        label_dir / f"{stem}_seg.nii.gz",
        label_dir / volume_path.name,
        label_dir / f"{stem}.nii.gz",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return None


def make_new_affine(old_affine, target_spacing):
    new_affine = old_affine.copy()

    for axis in range(3):
        direction = old_affine[:3, axis]
        norm = np.linalg.norm(direction)

        if norm > 0:
            new_affine[:3, axis] = direction / norm * target_spacing[axis]

    return new_affine


def resample_array(arr, original_spacing, target_spacing, order):
    zoom_factors = [
        original_spacing[i] / target_spacing[i]
        for i in range(3)
    ]

    return zoom(arr, zoom=zoom_factors, order=order)

In [11]:
def resample_sitk_image(
    sitk_image,
    target_spacing,
    interpolator,
    default_value=0,
):
    original_spacing = sitk_image.GetSpacing()
    original_size = sitk_image.GetSize()

    target_size = [
        int(round(original_size[i] * (original_spacing[i] / target_spacing[i])))
        for i in range(3)
    ]

    resampler = sitk.ResampleImageFilter()
    resampler.SetOutputSpacing(target_spacing)
    resampler.SetSize(target_size)
    resampler.SetOutputDirection(sitk_image.GetDirection())
    resampler.SetOutputOrigin(sitk_image.GetOrigin())
    resampler.SetTransform(sitk.Transform())
    resampler.SetDefaultPixelValue(default_value)
    resampler.SetInterpolator(interpolator)

    return resampler.Execute(sitk_image)

#### 주의: SimpleITK array shape은 (z, y, x)이고, image spacing은 (x, y, z)입니다. 위 코드는 SimpleITK 변환 규칙에 맞게 작동합니다.

In [12]:
def make_t11_t12_label(label_image):
    label_arr = sitk.GetArrayFromImage(label_image)

    target_arr = np.zeros_like(label_arr, dtype=np.uint8)
    target_arr[label_arr == T11_LABEL] = 1
    target_arr[label_arr == T12_LABEL] = 2

    target_image = sitk.GetImageFromArray(target_arr)
    target_image.CopyInformation(label_image)

    return target_image

In [13]:
df_t11_t12_final = pd.read_pickle("df_t11_t12_final_candidates.pkl")

print("Final candidates:", len(df_t11_t12_final))
display(df_t11_t12_final.groupby("source").size())

Final candidates: 939

source
COLONOG     752
COVID-19     37
MSD-T10     150
dtype: int64

In [17]:
df_t11_t12_final = pd.read_pickle("df_t11_t12_final_candidates.pkl")

MAX_CASES = None  # 테스트 후 None으로 변경

target_df = df_t11_t12_final.copy()

if MAX_CASES is not None:
    target_df = target_df.head(MAX_CASES)

rows = []

for idx, row in enumerate(target_df.itertuples(index=False), start=1):
    source = row.source
    file_name = row.file_name

    volume_path = VOLUME_ROOT / source / file_name
    label_path = find_label_path(volume_path)

    if label_path is None:
        print("Label not found:", file_name)
        continue

    img_nii = nib.load(volume_path)
    seg_nii = nib.load(label_path)

    image = np.asanyarray(img_nii.dataobj).astype(np.float32)
    seg = np.asanyarray(seg_nii.dataobj)

    original_spacing = img_nii.header.get_zooms()[:3]

    target_seg = np.zeros_like(seg, dtype=np.uint8)
    target_seg[seg == T11_LABEL] = 1
    target_seg[seg == T12_LABEL] = 2

    image_resampled = resample_array(
        image,
        original_spacing=original_spacing,
        target_spacing=TARGET_SPACING,
        order=1,
    ).astype(np.float32)

    label_resampled = resample_array(
        target_seg,
        original_spacing=original_spacing,
        target_spacing=TARGET_SPACING,
        order=0,
    ).astype(np.uint8)

    new_affine = make_new_affine(img_nii.affine, TARGET_SPACING)

    source_image_dir = OUTPUT_IMAGE_ROOT / source
    source_label_dir = OUTPUT_LABEL_ROOT / source

    source_image_dir.mkdir(parents=True, exist_ok=True)
    source_label_dir.mkdir(parents=True, exist_ok=True)

    output_image_path = source_image_dir / file_name
    output_label_path = source_label_dir / file_name.replace(".nii.gz", "_t11_t12.nii.gz")

    nib.save(
        nib.Nifti1Image(image_resampled, new_affine),
        output_image_path,
    )

    nib.save(
        nib.Nifti1Image(label_resampled, new_affine),
        output_label_path,
    )

    rows.append({
        "source": source,
        "patient_id": row.patient_id,
        "file_name": file_name,
        "input_image_path": str(volume_path),
        "input_label_path": str(label_path),
        "output_image_path": str(output_image_path),
        "output_label_path": str(output_label_path),
        "original_spacing": original_spacing,
        "target_spacing": TARGET_SPACING,
        "original_shape": image.shape,
        "resampled_shape": image_resampled.shape,
        "label_values": tuple(np.unique(label_resampled)),
    })

    print(f"[{idx}/{len(target_df)}] Saved:", file_name)

df_resample_log = pd.DataFrame(rows)
display(df_resample_log)

[1/939] Saved: 1.3.6.1.4.1.9328.50.4.0001.nii.gz
[2/939] Saved: 1.3.6.1.4.1.9328.50.4.0002.nii.gz
[3/939] Saved: 1.3.6.1.4.1.9328.50.4.0003.nii.gz
[4/939] Saved: 1.3.6.1.4.1.9328.50.4.0004.nii.gz
[5/939] Saved: 1.3.6.1.4.1.9328.50.4.0005.nii.gz
[6/939] Saved: 1.3.6.1.4.1.9328.50.4.0006.nii.gz
[7/939] Saved: 1.3.6.1.4.1.9328.50.4.0007.nii.gz
[8/939] Saved: 1.3.6.1.4.1.9328.50.4.0008.nii.gz
[9/939] Saved: 1.3.6.1.4.1.9328.50.4.0009.nii.gz
[10/939] Saved: 1.3.6.1.4.1.9328.50.4.0010.nii.gz
[11/939] Saved: 1.3.6.1.4.1.9328.50.4.0011.nii.gz
[12/939] Saved: 1.3.6.1.4.1.9328.50.4.0012.nii.gz
[13/939] Saved: 1.3.6.1.4.1.9328.50.4.0013.nii.gz
[14/939] Saved: 1.3.6.1.4.1.9328.50.4.0014.nii.gz
[15/939] Saved: 1.3.6.1.4.1.9328.50.4.0015.nii.gz
[16/939] Saved: 1.3.6.1.4.1.9328.50.4.0016.nii.gz
[17/939] Saved: 1.3.6.1.4.1.9328.50.4.0017.nii.gz
[18/939] Saved: 1.3.6.1.4.1.9328.50.4.0018.nii.gz
[19/939] Saved: 1.3.6.1.4.1.9328.50.4.0020.nii.gz
[20/939] Saved: 1.3.6.1.4.1.9328.50.4.0021.nii.gz
[21/939] Saved: 1.3.6.1.4.1.9328.50.4.0023.nii.gz
[22/939] Saved: 1.3.6.1.4.1.9328.50.4.0024.nii.gz
[23/939] Saved: 1.3.6.1.4.1.9328.50.4.0025.nii.gz
[24/939] Saved: 1.3.6.1.4.1.9328.50.4.0026.nii.gz
[25/939] Saved: 1.3.6.1.4.1.9328.50.4.0027.nii.gz
[26/939] Saved: 1.3.6.1.4.1.9328.50.4.0028.nii.gz
[27/939] Saved: 1.3.6.1.4.1.9328.50.4.0029.nii.gz
[28/939] Saved: 1.3.6.1.4.1.9328.50.4.0030.nii.gz
[29/939] Saved: 1.3.6.1.4.1.9328.50.4.0031.nii.gz
[30/939] Saved: 1.3.6.1.4.1.9328.50.4.0032.nii.gz
[31/939] Saved: 1.3.6.1.4.1.9328.50.4.0033.nii.gz
[32/939] Saved: 1.3.6.1.4.1.9328.50.4.0034.nii.gz
[33/939] Saved: 1.3.6.1.4.1.9328.50.4.0035.nii.gz
[34/939] Saved: 1.3.6.1.4.1.9328.50.4.0036.nii.gz
[35/939] Saved: 1.3.6.1.4.1.9328.50.4.0037.nii.gz
[36/939] Saved: 1.3.6.1.4.1.9328.50.4.0038.nii.gz
[37/939] Saved: 1.3.6.1.4.1.9328.50.4.0039.nii.gz
[38/939] Saved: 1.3.6.1.4.1.9328.50.4.0040.nii.gz
[39/939] Saved: 1.3.6.1.4.1.9328.50.4.0041.nii.gz
[40/939] Saved: 1.3.6.1.4.1.9328.50.4.0042.nii.gz
[41/939] Saved: 1.3.6.1.4.1.9328.50.4.0043.nii.gz
[42/939] Saved: 1.3.6.1.4.1.9328.50.4.0044.nii.gz
[43/939] Saved: 1.3.6.1.4.1.9328.50.4.0045.nii.gz
[44/939] Saved: 1.3.6.1.4.1.9328.50.4.0047.nii.gz
[45/939] Saved: 1.3.6.1.4.1.9328.50.4.0048.nii.gz
[46/939] Saved: 1.3.6.1.4.1.9328.50.4.0049.nii.gz
[47/939] Saved: 1.3.6.1.4.1.9328.50.4.0050.nii.gz
[48/939] Saved: 1.3.6.1.4.1.9328.50.4.0051.nii.gz
[49/939] Saved: 1.3.6.1.4.1.9328.50.4.0052.nii.gz
[50/939] Saved: 1.3.6.1.4.1.9328.50.4.0053.nii.gz
[51/939] Saved: 1.3.6.1.4.1.9328.50.4.0054.nii.gz
[52/939] Saved: 1.3.6.1.4.1.9328.50.4.0055.nii.gz
[53/939] Saved: 1.3.6.1.4.1.9328.50.4.0056.nii.gz
[54/939] Saved: 1.3.6.1.4.1.9328.50.4.0057.nii.gz
[55/939] Saved: 1.3.6.1.4.1.9328.50.4.0058.nii.gz
[56/939] Saved: 1.3.6.1.4.1.9328.50.4.0059.nii.gz
[57/939] Saved: 1.3.6.1.4.1.9328.50.4.0060.nii.gz
[58/939] Saved: 1.3.6.1.4.1.9328.50.4.0062.nii.gz
[59/939] Saved: 1.3.6.1.4.1.9328.50.4.0063.nii.gz
[60/939] Saved: 1.3.6.1.4.1.9328.50.4.0064.nii.gz
[61/939] Saved: 1.3.6.1.4.1.9328.50.4.0065.nii.gz
[62/939] Saved: 1.3.6.1.4.1.9328.50.4.0066.nii.gz
[63/939] Saved: 1.3.6.1.4.1.9328.50.4.0067.nii.gz
[64/939] Saved: 1.3.6.1.4.1.9328.50.4.0068.nii.gz
[65/939] Saved: 1.3.6.1.4.1.9328.50.4.0069.nii.gz
[66/939] Saved: 1.3.6.1.4.1.9328.50.4.0071.nii.gz
[67/939] Saved: 1.3.6.1.4.1.9328.50.4.0072.nii.gz
[68/939] Saved: 1.3.6.1.4.1.9328.50.4.0073.nii.gz
[69/939] Saved: 1.3.6.1.4.1.9328.50.4.0074.nii.gz
[70/939] Saved: 1.3.6.1.4.1.9328.50.4.0075.nii.gz
[71/939] Saved: 1.3.6.1.4.1.9328.50.4.0076.nii.gz
[72/939] Saved: 1.3.6.1.4.1.9328.50.4.0077.nii.gz
[73/939] Saved: 1.3.6.1.4.1.9328.50.4.0078.nii.gz
[74/939] Saved: 1.3.6.1.4.1.9328.50.4.0079.nii.gz
[75/939] Saved: 1.3.6.1.4.1.9328.50.4.0080.nii.gz
[76/939] Saved: 1.3.6.1.4.1.9328.50.4.0081.nii.gz
[77/939] Saved: 1.3.6.1.4.1.9328.50.4.0082.nii.gz
[78/939] Saved: 1.3.6.1.4.1.9328.50.4.0083.nii.gz
[79/939] Saved: 1.3.6.1.4.1.9328.50.4.0084.nii.gz
[80/939] Saved: 1.3.6.1.4.1.9328.50.4.0085.nii.gz
[81/939] Saved: 1.3.6.1.4.1.9328.50.4.0086.nii.gz
[82/939] Saved: 1.3.6.1.4.1.9328.50.4.0087.nii.gz
[83/939] Saved: 1.3.6.1.4.1.9328.50.4.0088.nii.gz
[84/939] Saved: 1.3.6.1.4.1.9328.50.4.0089.nii.gz
[85/939] Saved: 1.3.6.1.4.1.9328.50.4.0090.nii.gz
[86/939] Saved: 1.3.6.1.4.1.9328.50.4.0091.nii.gz
[87/939] Saved: 1.3.6.1.4.1.9328.50.4.0092.nii.gz
[88/939] Saved: 1.3.6.1.4.1.9328.50.4.0093.nii.gz
[89/939] Saved: 1.3.6.1.4.1.9328.50.4.0094.nii.gz
[90/939] Saved: 1.3.6.1.4.1.9328.50.4.0095.nii.gz
[91/939] Saved: 1.3.6.1.4.1.9328.50.4.0096.nii.gz
[92/939] Saved: 1.3.6.1.4.1.9328.50.4.0097.nii.gz
[93/939] Saved: 1.3.6.1.4.1.9328.50.4.0098.nii.gz
[94/939] Saved: 1.3.6.1.4.1.9328.50.4.0099.nii.gz
[95/939] Saved: 1.3.6.1.4.1.9328.50.4.0100.nii.gz
[96/939] Saved: 1.3.6.1.4.1.9328.50.4.0101.nii.gz
[97/939] Saved: 1.3.6.1.4.1.9328.50.4.0102.nii.gz
[98/939] Saved: 1.3.6.1.4.1.9328.50.4.0104.nii.gz
[99/939] Saved: 1.3.6.1.4.1.9328.50.4.0105.nii.gz
[100/939] Saved: 1.3.6.1.4.1.9328.50.4.0106.nii.gz
[101/939] Saved: 1.3.6.1.4.1.9328.50.4.0107.nii.gz
[102/939] Saved: 1.3.6.1.4.1.9328.50.4.0109.nii.gz
[103/939] Saved: 1.3.6.1.4.1.9328.50.4.0110.nii.gz
[104/939] Saved: 1.3.6.1.4.1.9328.50.4.0111.nii.gz
[105/939] Saved: 1.3.6.1.4.1.9328.50.4.0112.nii.gz
[106/939] Saved: 1.3.6.1.4.1.9328.50.4.0113.nii.gz
[107/939] Saved: 1.3.6.1.4.1.9328.50.4.0114.nii.gz
[108/939] Saved: 1.3.6.1.4.1.9328.50.4.0115.nii.gz
[109/939] Saved: 1.3.6.1.4.1.9328.50.4.0116.nii.gz
[110/939] Saved: 1.3.6.1.4.1.9328.50.4.0118.nii.gz
[111/939] Saved: 1.3.6.1.4.1.9328.50.4.0119.nii.gz
[112/939] Saved: 1.3.6.1.4.1.9328.50.4.0120.nii.gz
[113/939] Saved: 1.3.6.1.4.1.9328.50.4.0121.nii.gz
[114/939] Saved: 1.3.6.1.4.1.9328.50.4.0122.nii.gz
[115/939] Saved: 1.3.6.1.4.1.9328.50.4.0123.nii.gz
[116/939] Saved: 1.3.6.1.4.1.9328.50.4.0124.nii.gz
[117/939] Saved: 1.3.6.1.4.1.9328.50.4.0125.nii.gz
[118/939] Saved: 1.3.6.1.4.1.9328.50.4.0126.nii.gz
[119/939] Saved: 1.3.6.1.4.1.9328.50.4.0127.nii.gz
[120/939] Saved: 1.3.6.1.4.1.9328.50.4.0128.nii.gz
[121/939] Saved: 1.3.6.1.4.1.9328.50.4.0129.nii.gz
[122/939] Saved: 1.3.6.1.4.1.9328.50.4.0130.nii.gz
[123/939] Saved: 1.3.6.1.4.1.9328.50.4.0131.nii.gz
[124/939] Saved: 1.3.6.1.4.1.9328.50.4.0132.nii.gz
[125/939] Saved: 1.3.6.1.4.1.9328.50.4.0133.nii.gz
[126/939] Saved: 1.3.6.1.4.1.9328.50.4.0136.nii.gz
[127/939] Saved: 1.3.6.1.4.1.9328.50.4.0137.nii.gz
[128/939] Saved: 1.3.6.1.4.1.9328.50.4.0138.nii.gz
[129/939] Saved: 1.3.6.1.4.1.9328.50.4.0139.nii.gz
[130/939] Saved: 1.3.6.1.4.1.9328.50.4.0141.nii.gz
[131/939] Saved: 1.3.6.1.4.1.9328.50.4.0142.nii.gz
[132/939] Saved: 1.3.6.1.4.1.9328.50.4.0143.nii.gz
[133/939] Saved: 1.3.6.1.4.1.9328.50.4.0144.nii.gz
[134/939] Saved: 1.3.6.1.4.1.9328.50.4.0145.nii.gz
[135/939] Saved: 1.3.6.1.4.1.9328.50.4.0146.nii.gz
[136/939] Saved: 1.3.6.1.4.1.9328.50.4.0147.nii.gz
[137/939] Saved: 1.3.6.1.4.1.9328.50.4.0148.nii.gz
[138/939] Saved: 1.3.6.1.4.1.9328.50.4.0149.nii.gz
[139/939] Saved: 1.3.6.1.4.1.9328.50.4.0150.nii.gz
[140/939] Saved: 1.3.6.1.4.1.9328.50.4.0151.nii.gz
[141/939] Saved: 1.3.6.1.4.1.9328.50.4.0152.nii.gz
[142/939] Saved: 1.3.6.1.4.1.9328.50.4.0153.nii.gz
[143/939] Saved: 1.3.6.1.4.1.9328.50.4.0154.nii.gz
[144/939] Saved: 1.3.6.1.4.1.9328.50.4.0155.nii.gz
[145/939] Saved: 1.3.6.1.4.1.9328.50.4.0156.nii.gz
[146/939] Saved: 1.3.6.1.4.1.9328.50.4.0157.nii.gz
[147/939] Saved: 1.3.6.1.4.1.9328.50.4.0158.nii.gz
[148/939] Saved: 1.3.6.1.4.1.9328.50.4.0159.nii.gz
[149/939] Saved: 1.3.6.1.4.1.9328.50.4.0160.nii.gz
[150/939] Saved: 1.3.6.1.4.1.9328.50.4.0161.nii.gz
[151/939] Saved: 1.3.6.1.4.1.9328.50.4.0162.nii.gz
[152/939] Saved: 1.3.6.1.4.1.9328.50.4.0164.nii.gz
[153/939] Saved: 1.3.6.1.4.1.9328.50.4.0166.nii.gz
[154/939] Saved: 1.3.6.1.4.1.9328.50.4.0167.nii.gz
[155/939] Saved: 1.3.6.1.4.1.9328.50.4.0168.nii.gz
[156/939] Saved: 1.3.6.1.4.1.9328.50.4.0170.nii.gz
[157/939] Saved: 1.3.6.1.4.1.9328.50.4.0171.nii.gz
[158/939] Saved: 1.3.6.1.4.1.9328.50.4.0172.nii.gz
[159/939] Saved: 1.3.6.1.4.1.9328.50.4.0174.nii.gz
[160/939] Saved: 1.3.6.1.4.1.9328.50.4.0175.nii.gz
[161/939] Saved: 1.3.6.1.4.1.9328.50.4.0176.nii.gz
[162/939] Saved: 1.3.6.1.4.1.9328.50.4.0177.nii.gz
[163/939] Saved: 1.3.6.1.4.1.9328.50.4.0178.nii.gz
[164/939] Saved: 1.3.6.1.4.1.9328.50.4.0179.nii.gz
[165/939] Saved: 1.3.6.1.4.1.9328.50.4.0180.nii.gz
[166/939] Saved: 1.3.6.1.4.1.9328.50.4.0181.nii.gz
[167/939] Saved: 1.3.6.1.4.1.9328.50.4.0182.nii.gz
[168/939] Saved: 1.3.6.1.4.1.9328.50.4.0183.nii.gz
[169/939] Saved: 1.3.6.1.4.1.9328.50.4.0184.nii.gz
[170/939] Saved: 1.3.6.1.4.1.9328.50.4.0185.nii.gz
[171/939] Saved: 1.3.6.1.4.1.9328.50.4.0186.nii.gz
[172/939] Saved: 1.3.6.1.4.1.9328.50.4.0187.nii.gz
[173/939] Saved: 1.3.6.1.4.1.9328.50.4.0188.nii.gz
[174/939] Saved: 1.3.6.1.4.1.9328.50.4.0189.nii.gz
[175/939] Saved: 1.3.6.1.4.1.9328.50.4.0190.nii.gz
[176/939] Saved: 1.3.6.1.4.1.9328.50.4.0191.nii.gz
[177/939] Saved: 1.3.6.1.4.1.9328.50.4.0192.nii.gz
[178/939] Saved: 1.3.6.1.4.1.9328.50.4.0194.nii.gz
[179/939] Saved: 1.3.6.1.4.1.9328.50.4.0195.nii.gz
[180/939] Saved: 1.3.6.1.4.1.9328.50.4.0196.nii.gz
[181/939] Saved: 1.3.6.1.4.1.9328.50.4.0197.nii.gz
[182/939] Saved: 1.3.6.1.4.1.9328.50.4.0199.nii.gz
[183/939] Saved: 1.3.6.1.4.1.9328.50.4.0200.nii.gz
[184/939] Saved: 1.3.6.1.4.1.9328.50.4.0201.nii.gz
[185/939] Saved: 1.3.6.1.4.1.9328.50.4.0202.nii.gz
[186/939] Saved: 1.3.6.1.4.1.9328.50.4.0203.nii.gz
[187/939] Saved: 1.3.6.1.4.1.9328.50.4.0204.nii.gz
[188/939] Saved: 1.3.6.1.4.1.9328.50.4.0205.nii.gz
[189/939] Saved: 1.3.6.1.4.1.9328.50.4.0206.nii.gz
[190/939] Saved: 1.3.6.1.4.1.9328.50.4.0207.nii.gz
[191/939] Saved: 1.3.6.1.4.1.9328.50.4.0208.nii.gz
[192/939] Saved: 1.3.6.1.4.1.9328.50.4.0209.nii.gz
[193/939] Saved: 1.3.6.1.4.1.9328.50.4.0210.nii.gz
[194/939] Saved: 1.3.6.1.4.1.9328.50.4.0211.nii.gz
[195/939] Saved: 1.3.6.1.4.1.9328.50.4.0213.nii.gz
[196/939] Saved: 1.3.6.1.4.1.9328.50.4.0214.nii.gz
[197/939] Saved: 1.3.6.1.4.1.9328.50.4.0215.nii.gz
[198/939] Saved: 1.3.6.1.4.1.9328.50.4.0216.nii.gz
[199/939] Saved: 1.3.6.1.4.1.9328.50.4.0217.nii.gz
[200/939] Saved: 1.3.6.1.4.1.9328.50.4.0218.nii.gz
[201/939] Saved: 1.3.6.1.4.1.9328.50.4.0219.nii.gz
[202/939] Saved: 1.3.6.1.4.1.9328.50.4.0220.nii.gz
[203/939] Saved: 1.3.6.1.4.1.9328.50.4.0221.nii.gz
[204/939] Saved: 1.3.6.1.4.1.9328.50.4.0222.nii.gz
[205/939] Saved: 1.3.6.1.4.1.9328.50.4.0223.nii.gz
[206/939] Saved: 1.3.6.1.4.1.9328.50.4.0224.nii.gz
[207/939] Saved: 1.3.6.1.4.1.9328.50.4.0225.nii.gz
[208/939] Saved: 1.3.6.1.4.1.9328.50.4.0226.nii.gz
[209/939] Saved: 1.3.6.1.4.1.9328.50.4.0227.nii.gz
[210/939] Saved: 1.3.6.1.4.1.9328.50.4.0228.nii.gz
[211/939] Saved: 1.3.6.1.4.1.9328.50.4.0229.nii.gz
[212/939] Saved: 1.3.6.1.4.1.9328.50.4.0230.nii.gz
[213/939] Saved: 1.3.6.1.4.1.9328.50.4.0231.nii.gz
[214/939] Saved: 1.3.6.1.4.1.9328.50.4.0232.nii.gz
[215/939] Saved: 1.3.6.1.4.1.9328.50.4.0233.nii.gz
[216/939] Saved: 1.3.6.1.4.1.9328.50.4.0234.nii.gz
[217/939] Saved: 1.3.6.1.4.1.9328.50.4.0236.nii.gz
[218/939] Saved: 1.3.6.1.4.1.9328.50.4.0238.nii.gz
[219/939] Saved: 1.3.6.1.4.1.9328.50.4.0239.nii.gz
[220/939] Saved: 1.3.6.1.4.1.9328.50.4.0240.nii.gz
[221/939] Saved: 1.3.6.1.4.1.9328.50.4.0242.nii.gz
[222/939] Saved: 1.3.6.1.4.1.9328.50.4.0243.nii.gz
[223/939] Saved: 1.3.6.1.4.1.9328.50.4.0245.nii.gz
[224/939] Saved: 1.3.6.1.4.1.9328.50.4.0246.nii.gz
[225/939] Saved: 1.3.6.1.4.1.9328.50.4.0247.nii.gz
[226/939] Saved: 1.3.6.1.4.1.9328.50.4.0248.nii.gz
[227/939] Saved: 1.3.6.1.4.1.9328.50.4.0249.nii.gz
[228/939] Saved: 1.3.6.1.4.1.9328.50.4.0250.nii.gz
[229/939] Saved: 1.3.6.1.4.1.9328.50.4.0251.nii.gz
[230/939] Saved: 1.3.6.1.4.1.9328.50.4.0252.nii.gz
[231/939] Saved: 1.3.6.1.4.1.9328.50.4.0253.nii.gz
[232/939] Saved: 1.3.6.1.4.1.9328.50.4.0255.nii.gz
[233/939] Saved: 1.3.6.1.4.1.9328.50.4.0256.nii.gz
[234/939] Saved: 1.3.6.1.4.1.9328.50.4.0257.nii.gz
[235/939] Saved: 1.3.6.1.4.1.9328.50.4.0259.nii.gz
[236/939] Saved: 1.3.6.1.4.1.9328.50.4.0260.nii.gz
[237/939] Saved: 1.3.6.1.4.1.9328.50.4.0261.nii.gz
[238/939] Saved: 1.3.6.1.4.1.9328.50.4.0262.nii.gz
[239/939] Saved: 1.3.6.1.4.1.9328.50.4.0263.nii.gz
[240/939] Saved: 1.3.6.1.4.1.9328.50.4.0264.nii.gz
[241/939] Saved: 1.3.6.1.4.1.9328.50.4.0265.nii.gz
[242/939] Saved: 1.3.6.1.4.1.9328.50.4.0266.nii.gz
[243/939] Saved: 1.3.6.1.4.1.9328.50.4.0267.nii.gz
[244/939] Saved: 1.3.6.1.4.1.9328.50.4.0268.nii.gz
[245/939] Saved: 1.3.6.1.4.1.9328.50.4.0269.nii.gz
[246/939] Saved: 1.3.6.1.4.1.9328.50.4.0270.nii.gz
[247/939] Saved: 1.3.6.1.4.1.9328.50.4.0271.nii.gz
[248/939] Saved: 1.3.6.1.4.1.9328.50.4.0273.nii.gz
[249/939] Saved: 1.3.6.1.4.1.9328.50.4.0274.nii.gz
[250/939] Saved: 1.3.6.1.4.1.9328.50.4.0275.nii.gz
[251/939] Saved: 1.3.6.1.4.1.9328.50.4.0277.nii.gz
[252/939] Saved: 1.3.6.1.4.1.9328.50.4.0278.nii.gz
[253/939] Saved: 1.3.6.1.4.1.9328.50.4.0279.nii.gz
[254/939] Saved: 1.3.6.1.4.1.9328.50.4.0280.nii.gz
[255/939] Saved: 1.3.6.1.4.1.9328.50.4.0281.nii.gz
[256/939] Saved: 1.3.6.1.4.1.9328.50.4.0282.nii.gz
[257/939] Saved: 1.3.6.1.4.1.9328.50.4.0283.nii.gz
[258/939] Saved: 1.3.6.1.4.1.9328.50.4.0284.nii.gz
[259/939] Saved: 1.3.6.1.4.1.9328.50.4.0285.nii.gz
[260/939] Saved: 1.3.6.1.4.1.9328.50.4.0286.nii.gz
[261/939] Saved: 1.3.6.1.4.1.9328.50.4.0287.nii.gz
[262/939] Saved: 1.3.6.1.4.1.9328.50.4.0288.nii.gz
[263/939] Saved: 1.3.6.1.4.1.9328.50.4.0290.nii.gz
[264/939] Saved: 1.3.6.1.4.1.9328.50.4.0291.nii.gz
[265/939] Saved: 1.3.6.1.4.1.9328.50.4.0292.nii.gz
[266/939] Saved: 1.3.6.1.4.1.9328.50.4.0293.nii.gz
[267/939] Saved: 1.3.6.1.4.1.9328.50.4.0294.nii.gz
[268/939] Saved: 1.3.6.1.4.1.9328.50.4.0296.nii.gz
[269/939] Saved: 1.3.6.1.4.1.9328.50.4.0297.nii.gz
[270/939] Saved: 1.3.6.1.4.1.9328.50.4.0298.nii.gz
[271/939] Saved: 1.3.6.1.4.1.9328.50.4.0300.nii.gz
[272/939] Saved: 1.3.6.1.4.1.9328.50.4.0301.nii.gz
[273/939] Saved: 1.3.6.1.4.1.9328.50.4.0303.nii.gz
[274/939] Saved: 1.3.6.1.4.1.9328.50.4.0304.nii.gz
[275/939] Saved: 1.3.6.1.4.1.9328.50.4.0305.nii.gz
[276/939] Saved: 1.3.6.1.4.1.9328.50.4.0306.nii.gz
[277/939] Saved: 1.3.6.1.4.1.9328.50.4.0307.nii.gz
[278/939] Saved: 1.3.6.1.4.1.9328.50.4.0308.nii.gz
[279/939] Saved: 1.3.6.1.4.1.9328.50.4.0309.nii.gz
[280/939] Saved: 1.3.6.1.4.1.9328.50.4.0310.nii.gz
[281/939] Saved: 1.3.6.1.4.1.9328.50.4.0311.nii.gz
[282/939] Saved: 1.3.6.1.4.1.9328.50.4.0313.nii.gz
[283/939] Saved: 1.3.6.1.4.1.9328.50.4.0314.nii.gz
[284/939] Saved: 1.3.6.1.4.1.9328.50.4.0315.nii.gz
[285/939] Saved: 1.3.6.1.4.1.9328.50.4.0316.nii.gz
[286/939] Saved: 1.3.6.1.4.1.9328.50.4.0317.nii.gz
[287/939] Saved: 1.3.6.1.4.1.9328.50.4.0318.nii.gz
[288/939] Saved: 1.3.6.1.4.1.9328.50.4.0319.nii.gz
[289/939] Saved: 1.3.6.1.4.1.9328.50.4.0320.nii.gz
[290/939] Saved: 1.3.6.1.4.1.9328.50.4.0321.nii.gz
[291/939] Saved: 1.3.6.1.4.1.9328.50.4.0322.nii.gz
[292/939] Saved: 1.3.6.1.4.1.9328.50.4.0323.nii.gz
[293/939] Saved: 1.3.6.1.4.1.9328.50.4.0324.nii.gz
[294/939] Saved: 1.3.6.1.4.1.9328.50.4.0325.nii.gz
[295/939] Saved: 1.3.6.1.4.1.9328.50.4.0326.nii.gz
[296/939] Saved: 1.3.6.1.4.1.9328.50.4.0328.nii.gz
[297/939] Saved: 1.3.6.1.4.1.9328.50.4.0329.nii.gz
[298/939] Saved: 1.3.6.1.4.1.9328.50.4.0331.nii.gz
[299/939] Saved: 1.3.6.1.4.1.9328.50.4.0332.nii.gz
[300/939] Saved: 1.3.6.1.4.1.9328.50.4.0333.nii.gz
[301/939] Saved: 1.3.6.1.4.1.9328.50.4.0334.nii.gz
[302/939] Saved: 1.3.6.1.4.1.9328.50.4.0335.nii.gz
[303/939] Saved: 1.3.6.1.4.1.9328.50.4.0336.nii.gz
[304/939] Saved: 1.3.6.1.4.1.9328.50.4.0337.nii.gz
[305/939] Saved: 1.3.6.1.4.1.9328.50.4.0338.nii.gz
[306/939] Saved: 1.3.6.1.4.1.9328.50.4.0339.nii.gz
[307/939] Saved: 1.3.6.1.4.1.9328.50.4.0340.nii.gz
[308/939] Saved: 1.3.6.1.4.1.9328.50.4.0341.nii.gz
[309/939] Saved: 1.3.6.1.4.1.9328.50.4.0342.nii.gz
[310/939] Saved: 1.3.6.1.4.1.9328.50.4.0343.nii.gz
[311/939] Saved: 1.3.6.1.4.1.9328.50.4.0344.nii.gz
[312/939] Saved: 1.3.6.1.4.1.9328.50.4.0345.nii.gz
[313/939] Saved: 1.3.6.1.4.1.9328.50.4.0346.nii.gz
[314/939] Saved: 1.3.6.1.4.1.9328.50.4.0347.nii.gz
[315/939] Saved: 1.3.6.1.4.1.9328.50.4.0349.nii.gz
[316/939] Saved: 1.3.6.1.4.1.9328.50.4.0350.nii.gz
[317/939] Saved: 1.3.6.1.4.1.9328.50.4.0353.nii.gz
[318/939] Saved: 1.3.6.1.4.1.9328.50.4.0355.nii.gz
[319/939] Saved: 1.3.6.1.4.1.9328.50.4.0358.nii.gz
[320/939] Saved: 1.3.6.1.4.1.9328.50.4.0359.nii.gz
[321/939] Saved: 1.3.6.1.4.1.9328.50.4.0360.nii.gz
[322/939] Saved: 1.3.6.1.4.1.9328.50.4.0361.nii.gz
[323/939] Saved: 1.3.6.1.4.1.9328.50.4.0362.nii.gz
[324/939] Saved: 1.3.6.1.4.1.9328.50.4.0363.nii.gz
[325/939] Saved: 1.3.6.1.4.1.9328.50.4.0364.nii.gz
[326/939] Saved: 1.3.6.1.4.1.9328.50.4.0365.nii.gz
[327/939] Saved: 1.3.6.1.4.1.9328.50.4.0366.nii.gz
[328/939] Saved: 1.3.6.1.4.1.9328.50.4.0367.nii.gz
[329/939] Saved: 1.3.6.1.4.1.9328.50.4.0368.nii.gz
[330/939] Saved: 1.3.6.1.4.1.9328.50.4.0369.nii.gz
[331/939] Saved: 1.3.6.1.4.1.9328.50.4.0370.nii.gz
[332/939] Saved: 1.3.6.1.4.1.9328.50.4.0371.nii.gz
[333/939] Saved: 1.3.6.1.4.1.9328.50.4.0372.nii.gz
[334/939] Saved: 1.3.6.1.4.1.9328.50.4.0373.nii.gz
[335/939] Saved: 1.3.6.1.4.1.9328.50.4.0374.nii.gz
[336/939] Saved: 1.3.6.1.4.1.9328.50.4.0375.nii.gz
[337/939] Saved: 1.3.6.1.4.1.9328.50.4.0376.nii.gz
[338/939] Saved: 1.3.6.1.4.1.9328.50.4.0377.nii.gz
[339/939] Saved: 1.3.6.1.4.1.9328.50.4.0378.nii.gz
[340/939] Saved: 1.3.6.1.4.1.9328.50.4.0379.nii.gz
[341/939] Saved: 1.3.6.1.4.1.9328.50.4.0380.nii.gz
[342/939] Saved: 1.3.6.1.4.1.9328.50.4.0381.nii.gz
[343/939] Saved: 1.3.6.1.4.1.9328.50.4.0382.nii.gz
[344/939] Saved: 1.3.6.1.4.1.9328.50.4.0383.nii.gz
[345/939] Saved: 1.3.6.1.4.1.9328.50.4.0384.nii.gz
[346/939] Saved: 1.3.6.1.4.1.9328.50.4.0385.nii.gz
[347/939] Saved: 1.3.6.1.4.1.9328.50.4.0386.nii.gz
[348/939] Saved: 1.3.6.1.4.1.9328.50.4.0387.nii.gz
[349/939] Saved: 1.3.6.1.4.1.9328.50.4.0388.nii.gz
[350/939] Saved: 1.3.6.1.4.1.9328.50.4.0389.nii.gz
[351/939] Saved: 1.3.6.1.4.1.9328.50.4.0390.nii.gz
[352/939] Saved: 1.3.6.1.4.1.9328.50.4.0391.nii.gz
[353/939] Saved: 1.3.6.1.4.1.9328.50.4.0392.nii.gz
[354/939] Saved: 1.3.6.1.4.1.9328.50.4.0393.nii.gz
[355/939] Saved: 1.3.6.1.4.1.9328.50.4.0394.nii.gz
[356/939] Saved: 1.3.6.1.4.1.9328.50.4.0395.nii.gz
[357/939] Saved: 1.3.6.1.4.1.9328.50.4.0396.nii.gz
[358/939] Saved: 1.3.6.1.4.1.9328.50.4.0397.nii.gz
[359/939] Saved: 1.3.6.1.4.1.9328.50.4.0398.nii.gz
[360/939] Saved: 1.3.6.1.4.1.9328.50.4.0399.nii.gz
[361/939] Saved: 1.3.6.1.4.1.9328.50.4.0400.nii.gz
[362/939] Saved: 1.3.6.1.4.1.9328.50.4.0401.nii.gz
[363/939] Saved: 1.3.6.1.4.1.9328.50.4.0402.nii.gz
[364/939] Saved: 1.3.6.1.4.1.9328.50.4.0403.nii.gz
[365/939] Saved: 1.3.6.1.4.1.9328.50.4.0404.nii.gz
[366/939] Saved: 1.3.6.1.4.1.9328.50.4.0405.nii.gz
[367/939] Saved: 1.3.6.1.4.1.9328.50.4.0406.nii.gz
[368/939] Saved: 1.3.6.1.4.1.9328.50.4.0407.nii.gz
[369/939] Saved: 1.3.6.1.4.1.9328.50.4.0409.nii.gz
[370/939] Saved: 1.3.6.1.4.1.9328.50.4.0410.nii.gz
[371/939] Saved: 1.3.6.1.4.1.9328.50.4.0412.nii.gz
[372/939] Saved: 1.3.6.1.4.1.9328.50.4.0413.nii.gz
[373/939] Saved: 1.3.6.1.4.1.9328.50.4.0414.nii.gz
[374/939] Saved: 1.3.6.1.4.1.9328.50.4.0416.nii.gz
[375/939] Saved: 1.3.6.1.4.1.9328.50.4.0417.nii.gz
[376/939] Saved: 1.3.6.1.4.1.9328.50.4.0418.nii.gz
[377/939] Saved: 1.3.6.1.4.1.9328.50.4.0419.nii.gz
[378/939] Saved: 1.3.6.1.4.1.9328.50.4.0420.nii.gz
[379/939] Saved: 1.3.6.1.4.1.9328.50.4.0421.nii.gz
[380/939] Saved: 1.3.6.1.4.1.9328.50.4.0422.nii.gz
[381/939] Saved: 1.3.6.1.4.1.9328.50.4.0423.nii.gz
[382/939] Saved: 1.3.6.1.4.1.9328.50.4.0424.nii.gz
[383/939] Saved: 1.3.6.1.4.1.9328.50.4.0425.nii.gz
[384/939] Saved: 1.3.6.1.4.1.9328.50.4.0426.nii.gz
[385/939] Saved: 1.3.6.1.4.1.9328.50.4.0427.nii.gz
[386/939] Saved: 1.3.6.1.4.1.9328.50.4.0428.nii.gz
[387/939] Saved: 1.3.6.1.4.1.9328.50.4.0429.nii.gz
[388/939] Saved: 1.3.6.1.4.1.9328.50.4.0430.nii.gz
[389/939] Saved: 1.3.6.1.4.1.9328.50.4.0431.nii.gz
[390/939] Saved: 1.3.6.1.4.1.9328.50.4.0432.nii.gz
[391/939] Saved: 1.3.6.1.4.1.9328.50.4.0433.nii.gz
[392/939] Saved: 1.3.6.1.4.1.9328.50.4.0434.nii.gz
[393/939] Saved: 1.3.6.1.4.1.9328.50.4.0435.nii.gz
[394/939] Saved: 1.3.6.1.4.1.9328.50.4.0436.nii.gz

,source,patient_id,file_name,input_image_path,input_label_path,output_image_path,output_label_path,original_spacing,target_spacing,original_shape,resampled_shape,label_values
0,COLONOG,1.3.6.1.4.1.9328.50.4.0001,1.3.6.1.4.1.9328.50.4.0001.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.78125, 0.78125, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 604)","(400, 400, 242)","(0, 1, 2)"
1,COLONOG,1.3.6.1.4.1.9328.50.4.0002,1.3.6.1.4.1.9328.50.4.0002.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.78125, 0.78125, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 637)","(400, 400, 255)","(0, 1, 2)"
2,COLONOG,1.3.6.1.4.1.9328.50.4.0003,1.3.6.1.4.1.9328.50.4.0003.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.78125, 0.78125, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 663)","(400, 400, 265)","(0, 1, 2)"
3,COLONOG,1.3.6.1.4.1.9328.50.4.0004,1.3.6.1.4.1.9328.50.4.0004.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.78125, 0.78125, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 520)","(400, 400, 208)","(0, 1, 2)"
4,COLONOG,1.3.6.1.4.1.9328.50.4.0005,1.3.6.1.4.1.9328.50.4.0005.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.60546875, 0.60546875, 1.0)","(1.0, 1.0, 2.0)","(512, 512, 401)","(310, 310, 200)","(0, 1, 2)"
...,...,...,...,...,...,...,...,...,...,...,...,...
934,MSD-T10,liver_95,liver_95.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.738, 0.738, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 841)","(378, 378, 336)","(0, 1, 2)"
935,MSD-T10,liver_96,liver_96.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.74609375, 0.74609375, 0.7)","(1.0, 1.0, 2.0)","(512, 512, 722)","(382, 382, 253)","(0, 1, 2)"
936,MSD-T10,liver_97,liver_97.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.72265625, 0.72265625, 0.7)","(1.0, 1.0, 2.0)","(512, 512, 671)","(370, 370, 235)","(0, 1, 2)"
937,MSD-T10,liver_98,liver_98.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.734375, 0.734375, 0.7)","(1.0, 1.0, 2.0)","(512, 512, 645)","(376, 376, 226)","(0, 1, 2)"
938,MSD-T10,liver_99,liver_99.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,"(0.78125, 0.78125, 0.6999841)","(1.0, 1.0, 2.0)","(512, 512, 629)","(400, 400, 220)","(0, 1, 2)"

In [15]:
df_resample_log[["source", "file_name", "original_spacing", "target_spacing", "original_shape", "resampled_shape", "label_values"]]

,source,file_name,original_spacing,target_spacing,original_shape,resampled_shape,label_values
0,COLONOG,1.3.6.1.4.1.9328.50.4.0001.nii.gz,"(0.78125, 0.78125, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 604)","(400, 400, 242)","(0, 1, 2)"
1,COLONOG,1.3.6.1.4.1.9328.50.4.0002.nii.gz,"(0.78125, 0.78125, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 637)","(400, 400, 255)","(0, 1, 2)"
2,COLONOG,1.3.6.1.4.1.9328.50.4.0003.nii.gz,"(0.78125, 0.78125, 0.8)","(1.0, 1.0, 2.0)","(512, 512, 663)","(400, 400, 265)","(0, 1, 2)"

In [16]:
for _, row in df_resample_log.iterrows():
    img = nib.load(row["output_image_path"])
    seg = nib.load(row["output_label_path"])

    print(row["file_name"])
    print("image shape:", img.shape)
    print("label shape:", seg.shape)
    print("same shape:", img.shape == seg.shape)
    print("label values:", np.unique(np.asanyarray(seg.dataobj)))
    print()

1.3.6.1.4.1.9328.50.4.0001.nii.gz
image shape: (400, 400, 242)
label shape: (400, 400, 242)
same shape: True
label values: [0 1 2]

1.3.6.1.4.1.9328.50.4.0002.nii.gz
image shape: (400, 400, 255)
label shape: (400, 400, 255)
same shape: True
label values: [0 1 2]

1.3.6.1.4.1.9328.50.4.0003.nii.gz
image shape: (400, 400, 265)
label shape: (400, 400, 265)
same shape: True
label values: [0 1 2]

In [21]:
from pathlib import Path
import nibabel as nib
import numpy as np
import pandas as pd

OUTPUT_ROOT = Path(r"C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\t11_t12_resampled_1x1x2")
OUTPUT_IMAGE_ROOT = OUTPUT_ROOT / "images"
OUTPUT_LABEL_ROOT = OUTPUT_ROOT / "labels"

rows = []

for image_path in sorted(OUTPUT_IMAGE_ROOT.rglob("*.nii.gz")):
    source = image_path.parent.name
    file_name = image_path.name

    label_path = OUTPUT_LABEL_ROOT / source / file_name.replace(".nii.gz", "_t11_t12.nii.gz")

    image_exists = image_path.exists()
    label_exists = label_path.exists()

    if not label_exists:
        rows.append({
            "source": source,
            "file_name": file_name,
            "image_exists": image_exists,
            "label_exists": False,
        })
        continue

    img = nib.load(image_path)
    seg = nib.load(label_path)

    label_values = tuple(np.unique(np.asanyarray(seg.dataobj)).astype(int))

    rows.append({
        "source": source,
        "file_name": file_name,
        "image_path": image_path,
        "label_path": label_path,
        "image_exists": image_exists,
        "label_exists": label_exists,
        "image_shape": img.shape,
        "label_shape": seg.shape,
        "same_shape": img.shape == seg.shape,
        "image_spacing": img.header.get_zooms()[:3],
        "label_spacing": seg.header.get_zooms()[:3],
        "label_values": label_values,
        "has_T11": 1 in label_values,
        "has_T12": 2 in label_values,
        "t11_voxels": int(np.sum(np.asanyarray(seg.dataobj) == 1)),
        "t12_voxels": int(np.sum(np.asanyarray(seg.dataobj) == 2)),
    })

df_resampled_check = pd.DataFrame(rows)

display(df_resampled_check.head())
print("Checked:", len(df_resampled_check))

,source,file_name,image_path,label_path,image_exists,label_exists,image_shape,label_shape,same_shape,image_spacing,label_spacing,label_values,has_T11,has_T12,t11_voxels,t12_voxels
0,COLONOG,1.3.6.1.4.1.9328.50.4.0001.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,True,True,"(400, 400, 242)","(400, 400, 242)",True,"(1.0, 1.0, 2.0)","(1.0, 1.0, 2.0)","(0, 1, 2)",True,True,16555,19356
1,COLONOG,1.3.6.1.4.1.9328.50.4.0002.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,True,True,"(400, 400, 255)","(400, 400, 255)",True,"(1.0, 1.0, 2.0)","(1.0, 1.0, 2.0)","(0, 1, 2)",True,True,29404,32622
2,COLONOG,1.3.6.1.4.1.9328.50.4.0003.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,True,True,"(400, 400, 265)","(400, 400, 265)",True,"(1.0, 1.0, 2.0)","(1.0, 1.0, 2.0)","(0, 1, 2)",True,True,23154,26119
3,COLONOG,1.3.6.1.4.1.9328.50.4.0004.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,True,True,"(400, 400, 208)","(400, 400, 208)",True,"(1.0, 1.0, 2.0)","(1.0, 1.0, 2.0)","(0, 1, 2)",True,True,20115,21226
4,COLONOG,1.3.6.1.4.1.9328.50.4.0005.nii.gz,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,C:\Users\comds\Desktop\졸업작품\dataset\CTSpine1K\...,True,True,"(310, 310, 200)","(310, 310, 200)",True,"(1.0, 1.0, 2.0)","(1.0, 1.0, 2.0)","(0, 1, 2)",True,True,26675,28035

Checked: 939

In [22]:
print("Total:", len(df_resampled_check))
print("Missing labels:", (~df_resampled_check["label_exists"]).sum())
print("Shape mismatch:", (~df_resampled_check["same_shape"]).sum())
print("Missing T11:", (~df_resampled_check["has_T11"]).sum())
print("Missing T12:", (~df_resampled_check["has_T12"]).sum())

display(df_resampled_check["label_values"].value_counts())

Total: 939
Missing labels: 0
Shape mismatch: 0
Missing T11: 0
Missing T12: 0

label_values
(0, 1, 2)    939
Name: count, dtype: int64

In [23]:
display(
    df_resampled_check
    .groupby("source")
    .size()
    .rename("n_resampled")
    .to_frame()
)

          n_resampled
source
COLONOG           752
COVID-19           37
MSD-T10           150

In [24]:
display(
    df_resampled_check[["image_spacing", "label_spacing"]]
    .head()
)

     image_spacing    label_spacing
0  (1.0, 1.0, 2.0)  (1.0, 1.0, 2.0)
1  (1.0, 1.0, 2.0)  (1.0, 1.0, 2.0)
2  (1.0, 1.0, 2.0)  (1.0, 1.0, 2.0)
3  (1.0, 1.0, 2.0)  (1.0, 1.0, 2.0)
4  (1.0, 1.0, 2.0)  (1.0, 1.0, 2.0)

In [25]:
problem_cases = df_resampled_check[
    (~df_resampled_check["label_exists"]) |
    (~df_resampled_check["same_shape"]) |
    (~df_resampled_check["has_T11"]) |
    (~df_resampled_check["has_T12"])
]

display(problem_cases)

Empty DataFrame
Columns: [source, file_name, image_path, label_path, image_exists, label_exists, image_shape, label_shape, same_shape, image_spacing, label_spacing, label_values, has_T11, has_T12, t11_voxels, t12_voxels]
Index: []

In [26]:
df_resampled_check.to_csv(
    OUTPUT_ROOT / "resampled_sanity_check.csv",
    index=False,
    encoding="utf-8-sig",
)

df_resampled_check.to_pickle(
    OUTPUT_ROOT / "resampled_sanity_check.pkl"
)

## segmentation학습 전 crop 수행 해야됨